services:
  postgres:
    image: postgres:16.4-alpine
    container_name: team_saas_postgres
    environment:
      POSTGRES_DB: team-saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54324:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
